name       : streamlink
version    : 0.3.0
release    : 3
source     :
    - https://github.com/streamlink/streamlink/archive/0.3.0.tar.gz : 8f33c1d1122c8b0cbab6b046b2a9a47b734b64a5e265cb828cf33aca74b89ba8
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python3-pycryptodome
build      : |
    %python3_setup
install    : |
    %python3_install
