name       : streamlink
version    : 0.8.1
release    : 9
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.8.1/streamlink-0.8.1.tar.gz : c0a487fa1c6b1d07008a1a4d5739df68a9e0c59cf06054715c13c1e3bed5a436
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming
    services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - pkgconfig(python-3.5)
    - python3-pycryptodome
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-setuptools
    - python-sphinx
    - python-websocket-client
rundeps    :
    - python3-pycryptodome
    - python-pycountry
    - python-pysocks
    - python-websocket-client
build      : |
    %python3_setup build_sphinx -b man
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
    install -Dm644 __py3_build/sphinx/man/streamlink.1 $installdir/usr/share/man/man1/streamlink.1
check      : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_setup test
