name       : streamlink
version    : 0.9.0
release    : 10
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.9.0/streamlink-0.9.0.tar.gz : 8c01c23a3e02d75a09232ac471a7c277a699455293a99e8a2ec0846a1b4a6819
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - pkgconfig(python-3.5)
    - python3-pycryptodome
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-setuptools
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup build_sphinx -b man
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
    install -Dm644 __py3_build/sphinx/man/streamlink.1 $installdir/usr/share/man/man1/streamlink.1
check      : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_setup test
