name       : streamlink
version    : 0.0.2
release    : 1
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.0.2/streamlink-0.0.2.tar.gz : c443f46cfca540ecd04b6439e337d466f3bf9fc0df074bcfa69ad27ddb63c7a4
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - python-setuptools
rundeps    :
    - python-singledispatch
build      : |
    %python_setup    
install    : |
    %python_install
