name       : streamlink
version    : 0.6.0
release    : 7
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.6.0/streamlink-0.6.0.tar.gz : 945a6a0e9e8c3965a83579506219baaa2f89801d463002650d8206adfa39a072
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python3-pycryptodome
    - python-pycountry
build      : |
    %python3_setup
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
