name       : streamlink
version    : 2.1.1
release    : 27
source     :
    - https://github.com/streamlink/streamlink/archive/refs/tags/2.1.1.tar.gz : 5fe3dc899f200ada9b58f7ad2e08f6d40c6ea312906ad1e340c009c72c12be8f
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
