name       : streamlink
version    : 0.3.2
release    : 4
source     :
    - https://github.com/streamlink/streamlink/archive/0.3.2.tar.gz : b126a0d2c964a513c3b5474b457bc5faf3dbb17aa8b43c4c8f6d633e29b2738e
license    : BSD-2-Clause
component  : network.clients
summary    : Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python3-pycryptodome
    - python-pycountry
setup      : |
    %patch -p1 < $pkgfiles/choose-pycountry-as-dep-env-var.patch
build      : |
    %python3_setup
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
