name       : streamlink
version    : 3.1.1
release    : 37
source     :
    - https://github.com/streamlink/streamlink/releases/download/3.1.1/streamlink-3.1.1.tar.gz : 855cd31e900e3ae1d5328a37123bfffe2aec501a1d74bcdd12f0d2a2758060e4
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-recommonmark
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-pycountry
    - python-pysocks
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
