name       : streamlink
version    : 6.2.0
release    : 52
source     :
    - https://github.com/streamlink/streamlink/releases/download/6.2.0/streamlink-6.2.0.tar.gz : aeae1b7848446f90998c62324e7107c8f41f8c08266dbc419b81e1cc1b35559a
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
networking : yes
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-freezegun # check
    - python-isodate
    - python-lxml
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest-asyncio # check
    - python-pytest-mock # check
    - python-requests # check
    - python-requests-mock # check
    - python-tomli
    - python-trio-websocket
    - python-typing-extensions
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-pycountry
    - python-pysocks
    - python-trio-websocket
    - python-typing-extensions
    - python-websocket-client
build      : |
    # We don't have versioningit in the repo so build like this for now
    # loving all these new pep517/518 build systems
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    python3 -m pip install --user versioningit
    python3 -m pip wheel --no-deps .
install    : |
    python3 -m pip install --root=%installroot% --no-deps *.whl
#check      : |
#    Most of tests/webbrowser/ failing
#    %python3_test pytest3
