name       : streamlink
version    : 2.4.0
release    : 32
source     :
    - https://github.com/streamlink/streamlink/releases/download/2.4.0/streamlink-2.4.0.tar.gz : e95588e222d1a7bd51e3171cd4bce84fd6f646418537aff37993d40f597810af
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-recommonmark
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup
    %python3_setup build_sphinx -b man
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
