name       : streamlink
version    : 2.3.0
release    : 31
source     :
    - https://github.com/streamlink/streamlink/releases/download/2.3.0/streamlink-2.3.0.tar.gz : 1497e6dc5d2fb8c5b17688f20ca2e8989a279de804a4de37d2107af33b9faa04
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-recommonmark
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup
    %python3_setup build_sphinx -b man
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
