name       : streamlink
version    : 3.0.0
release    : 33
source     :
    - https://github.com/streamlink/streamlink/releases/download/3.0.0/streamlink-3.0.0.tar.gz : ef5bcd6d7b854aac95d051886c0e189a4b03acd54dbbadb476566bd292c24b6f
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
replaces   :
    - livestreamer
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-recommonmark
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-lxml
    - python-pycountry
    - python-pysocks
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
