name       : streamlink
version    : 0.10.0
release    : 12
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.10.0/streamlink-0.10.0.tar.gz : 8bc06e53ab15fab57f782ea438a5f00c4807148b21f8fbed9238ed4865e08e24
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player
    of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - python3-pycryptodome
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-setuptools
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup build_sphinx -b man
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
    install -Dm00644 $PKG_BUILD_DIR/py3build/build/sphinx/man/streamlink.1 $installdir/usr/share/man/man1/streamlink.1
check      : |
    export STREAMLINK_USE_PYCOUNTRY=1
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
