name       : streamlink
version    : 0.14.0
release    : 17
source     :
    - https://github.com/streamlink/streamlink/releases/download/0.14.0/streamlink-0.14.0.tar.gz : 0b594d4a10d5d2eea340af3878ea0da98ccbbb13515d158301c4582c72ea4e75
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-setuptools
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
replaces   :
    - livestreamer
