name       : streamlink
version    : 1.0.0
release    : 19
source     :
    - https://github.com/streamlink/streamlink/releases/download/1.0.0/streamlink-1.0.0.tar.gz : b0a355add636c37531efc76e784d1c9e390f3d171f039e07a6be717eb956bfc7
license    : BSD-2-Clause
component  : network.clients
summary    : Extracts streams from various services and pipes them into a video player of choice
description: |
    Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, or alternatively, a browser
builddeps  :
    - python3-pycryptodome
    - python-isodate
    - python-mock
    - python-pycountry
    - python-pysocks
    - python-pytest
    - python-requests-mock
    - python-setuptools
    - python-sphinx
    - python-websocket-client
rundeps    :
    - ffmpeg
    - python3-pycryptodome
    - python-isodate
    - python-pycountry
    - python-pysocks
    - python-websocket-client
    - rtmpdump
build      : |
    %python3_setup
install    : |
    export STREAMLINK_USE_PYCOUNTRY=1
    %python3_install
replaces   :
    - livestreamer
